// Code generated by MockGen. DO NOT EDIT.
// Source: update_user.usecase.go
//
// Generated by this command:
//
//	mockgen -source update_user.usecase.go -package domain_usecase -destination /home/fernandoviana/Documentos/Appointment-Platform/backend/test/mocks/domain_usecase/mock_update_user.usecase.go
//

// Package domain_usecase is a generated GoMock package.
package domain_usecase

import (
	dto "appointment-platform-backend-backend/internal/domain/dto"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUpdateUserUsecaseInterface is a mock of UpdateUserUsecaseInterface interface.
type MockUpdateUserUsecaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateUserUsecaseInterfaceMockRecorder
	isgomock struct{}
}

// MockUpdateUserUsecaseInterfaceMockRecorder is the mock recorder for MockUpdateUserUsecaseInterface.
type MockUpdateUserUsecaseInterfaceMockRecorder struct {
	mock *MockUpdateUserUsecaseInterface
}

// NewMockUpdateUserUsecaseInterface creates a new mock instance.
func NewMockUpdateUserUsecaseInterface(ctrl *gomock.Controller) *MockUpdateUserUsecaseInterface {
	mock := &MockUpdateUserUsecaseInterface{ctrl: ctrl}
	mock.recorder = &MockUpdateUserUsecaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateUserUsecaseInterface) EXPECT() *MockUpdateUserUsecaseInterfaceMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockUpdateUserUsecaseInterface) Execute(ctx context.Context, input dto.UpdateUserInputDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockUpdateUserUsecaseInterfaceMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockUpdateUserUsecaseInterface)(nil).Execute), ctx, input)
}
