// Code generated by MockGen. DO NOT EDIT.
// Source: get_user_profile.usecase.go
//
// Generated by this command:
//
//	mockgen -source get_user_profile.usecase.go -package domain_usecase -destination /home/fernandoviana/Documentos/Appointment-Platform/backend/test/mocks/domain_usecase/mock_get_user_profile.usecase.go
//

// Package domain_usecase is a generated GoMock package.
package domain_usecase

import (
	dto "appointment-platform-backend-backend/internal/domain/dto"
	domain_response "appointment-platform-backend-backend/internal/domain/response"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGetUserProfileUsecaseInterface is a mock of GetUserProfileUsecaseInterface interface.
type MockGetUserProfileUsecaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockGetUserProfileUsecaseInterfaceMockRecorder
	isgomock struct{}
}

// MockGetUserProfileUsecaseInterfaceMockRecorder is the mock recorder for MockGetUserProfileUsecaseInterface.
type MockGetUserProfileUsecaseInterfaceMockRecorder struct {
	mock *MockGetUserProfileUsecaseInterface
}

// NewMockGetUserProfileUsecaseInterface creates a new mock instance.
func NewMockGetUserProfileUsecaseInterface(ctrl *gomock.Controller) *MockGetUserProfileUsecaseInterface {
	mock := &MockGetUserProfileUsecaseInterface{ctrl: ctrl}
	mock.recorder = &MockGetUserProfileUsecaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetUserProfileUsecaseInterface) EXPECT() *MockGetUserProfileUsecaseInterfaceMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetUserProfileUsecaseInterface) Execute(ctx context.Context, input dto.GetUserInputDto) (*domain_response.GetUserProfileResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(*domain_response.GetUserProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetUserProfileUsecaseInterfaceMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetUserProfileUsecaseInterface)(nil).Execute), ctx, input)
}
