// Code generated by MockGen. DO NOT EDIT.
// Source: create_appointment.go
//
// Generated by this command:
//
//	mockgen -source create_appointment.go -package domain_usecase_appointment -destination /home/fernandoviana/Documentos/Appointment-Platform/backend/test/mocks/domain_usecase_appointment/mock_create_appointment.go
//

// Package domain_usecase_appointment is a generated GoMock package.
package domain_usecase_appointment

import (
	dto "appointment-platform-backend-backend/internal/domain/dto"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCreateAppointmentUsecaseInterface is a mock of CreateAppointmentUsecaseInterface interface.
type MockCreateAppointmentUsecaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCreateAppointmentUsecaseInterfaceMockRecorder
	isgomock struct{}
}

// MockCreateAppointmentUsecaseInterfaceMockRecorder is the mock recorder for MockCreateAppointmentUsecaseInterface.
type MockCreateAppointmentUsecaseInterfaceMockRecorder struct {
	mock *MockCreateAppointmentUsecaseInterface
}

// NewMockCreateAppointmentUsecaseInterface creates a new mock instance.
func NewMockCreateAppointmentUsecaseInterface(ctrl *gomock.Controller) *MockCreateAppointmentUsecaseInterface {
	mock := &MockCreateAppointmentUsecaseInterface{ctrl: ctrl}
	mock.recorder = &MockCreateAppointmentUsecaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateAppointmentUsecaseInterface) EXPECT() *MockCreateAppointmentUsecaseInterfaceMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCreateAppointmentUsecaseInterface) Execute(ctx context.Context, input dto.CreateAppointmentInputDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockCreateAppointmentUsecaseInterfaceMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCreateAppointmentUsecaseInterface)(nil).Execute), ctx, input)
}
