// Code generated by MockGen. DO NOT EDIT.
// Source: delete_appointment.go
//
// Generated by this command:
//
//	mockgen -source delete_appointment.go -package domain_usecase_appointment -destination /home/fernandoviana/Documentos/Appointment-Platform/backend/test/mocks/domain_usecase_appointment/mock_delete_appointment.go
//

// Package domain_usecase_appointment is a generated GoMock package.
package domain_usecase_appointment

import (
	dto "appointment-platform-backend-backend/internal/domain/dto"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDeleteAppointmentUsecaseInterface is a mock of DeleteAppointmentUsecaseInterface interface.
type MockDeleteAppointmentUsecaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteAppointmentUsecaseInterfaceMockRecorder
	isgomock struct{}
}

// MockDeleteAppointmentUsecaseInterfaceMockRecorder is the mock recorder for MockDeleteAppointmentUsecaseInterface.
type MockDeleteAppointmentUsecaseInterfaceMockRecorder struct {
	mock *MockDeleteAppointmentUsecaseInterface
}

// NewMockDeleteAppointmentUsecaseInterface creates a new mock instance.
func NewMockDeleteAppointmentUsecaseInterface(ctrl *gomock.Controller) *MockDeleteAppointmentUsecaseInterface {
	mock := &MockDeleteAppointmentUsecaseInterface{ctrl: ctrl}
	mock.recorder = &MockDeleteAppointmentUsecaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteAppointmentUsecaseInterface) EXPECT() *MockDeleteAppointmentUsecaseInterfaceMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockDeleteAppointmentUsecaseInterface) Execute(ctx context.Context, input dto.DeleteAppointmentInputDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockDeleteAppointmentUsecaseInterfaceMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockDeleteAppointmentUsecaseInterface)(nil).Execute), ctx, input)
}
