// Code generated by MockGen. DO NOT EDIT.
// Source: set_appointment_status.go
//
// Generated by this command:
//
//	mockgen -source set_appointment_status.go -package domain_usecase_appointment -destination /home/fernandoviana/Documentos/Appointment-Platform/backend/test/mocks/domain_usecase_appointment/mock_set_appointment_status.go
//

// Package domain_usecase_appointment is a generated GoMock package.
package domain_usecase_appointment

import (
	dto "appointment-platform-backend-backend/internal/domain/dto"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSetAppointmentStatusUsecaseInterface is a mock of SetAppointmentStatusUsecaseInterface interface.
type MockSetAppointmentStatusUsecaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSetAppointmentStatusUsecaseInterfaceMockRecorder
	isgomock struct{}
}

// MockSetAppointmentStatusUsecaseInterfaceMockRecorder is the mock recorder for MockSetAppointmentStatusUsecaseInterface.
type MockSetAppointmentStatusUsecaseInterfaceMockRecorder struct {
	mock *MockSetAppointmentStatusUsecaseInterface
}

// NewMockSetAppointmentStatusUsecaseInterface creates a new mock instance.
func NewMockSetAppointmentStatusUsecaseInterface(ctrl *gomock.Controller) *MockSetAppointmentStatusUsecaseInterface {
	mock := &MockSetAppointmentStatusUsecaseInterface{ctrl: ctrl}
	mock.recorder = &MockSetAppointmentStatusUsecaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSetAppointmentStatusUsecaseInterface) EXPECT() *MockSetAppointmentStatusUsecaseInterfaceMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockSetAppointmentStatusUsecaseInterface) Execute(ctx context.Context, input dto.SetAppointmentStatusInputDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockSetAppointmentStatusUsecaseInterfaceMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockSetAppointmentStatusUsecaseInterface)(nil).Execute), ctx, input)
}
