// Code generated by MockGen. DO NOT EDIT.
// Source: create_patient.go
//
// Generated by this command:
//
//	mockgen -source create_patient.go -package domain_usecase_patient -destination /home/fernandoviana/Documentos/Appointment-Platform/backend/test/mocks/domain_usecase_patient/mock_create_patient.go
//

// Package domain_usecase_patient is a generated GoMock package.
package domain_usecase_patient

import (
	dto "appointment-platform-backend-backend/internal/domain/dto"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCreatePatientUsecaseInterface is a mock of CreatePatientUsecaseInterface interface.
type MockCreatePatientUsecaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCreatePatientUsecaseInterfaceMockRecorder
	isgomock struct{}
}

// MockCreatePatientUsecaseInterfaceMockRecorder is the mock recorder for MockCreatePatientUsecaseInterface.
type MockCreatePatientUsecaseInterfaceMockRecorder struct {
	mock *MockCreatePatientUsecaseInterface
}

// NewMockCreatePatientUsecaseInterface creates a new mock instance.
func NewMockCreatePatientUsecaseInterface(ctrl *gomock.Controller) *MockCreatePatientUsecaseInterface {
	mock := &MockCreatePatientUsecaseInterface{ctrl: ctrl}
	mock.recorder = &MockCreatePatientUsecaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreatePatientUsecaseInterface) EXPECT() *MockCreatePatientUsecaseInterfaceMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCreatePatientUsecaseInterface) Execute(ctx context.Context, input dto.CreatePatientInputDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockCreatePatientUsecaseInterfaceMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCreatePatientUsecaseInterface)(nil).Execute), ctx, input)
}
