// Code generated by MockGen. DO NOT EDIT.
// Source: list_patient.go
//
// Generated by this command:
//
//	mockgen -source list_patient.go -package domain_usecase_patient -destination /home/fernandoviana/Documentos/Appointment-Platform/backend/test/mocks/domain_usecase_patient/mock_list_patient.go
//

// Package domain_usecase_patient is a generated GoMock package.
package domain_usecase_patient

import (
	dto "appointment-platform-backend-backend/internal/domain/dto"
	domain_response "appointment-platform-backend-backend/internal/domain/response"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockListPatientUsecaseInterface is a mock of ListPatientUsecaseInterface interface.
type MockListPatientUsecaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockListPatientUsecaseInterfaceMockRecorder
	isgomock struct{}
}

// MockListPatientUsecaseInterfaceMockRecorder is the mock recorder for MockListPatientUsecaseInterface.
type MockListPatientUsecaseInterfaceMockRecorder struct {
	mock *MockListPatientUsecaseInterface
}

// NewMockListPatientUsecaseInterface creates a new mock instance.
func NewMockListPatientUsecaseInterface(ctrl *gomock.Controller) *MockListPatientUsecaseInterface {
	mock := &MockListPatientUsecaseInterface{ctrl: ctrl}
	mock.recorder = &MockListPatientUsecaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListPatientUsecaseInterface) EXPECT() *MockListPatientUsecaseInterfaceMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockListPatientUsecaseInterface) Execute(ctx context.Context, input dto.ListPatientInputDto) (domain_response.ListPatientsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(domain_response.ListPatientsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockListPatientUsecaseInterfaceMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockListPatientUsecaseInterface)(nil).Execute), ctx, input)
}
