// Code generated by MockGen. DO NOT EDIT.
// Source: delete_patient.go
//
// Generated by this command:
//
//	mockgen -source delete_patient.go -package domain_usecase_patient -destination /home/fernandoviana/Documentos/Appointment-Platform/backend/test/mocks/domain_usecase_patient/mock_delete_patient.go
//

// Package domain_usecase_patient is a generated GoMock package.
package domain_usecase_patient

import (
	dto "appointment-platform-backend-backend/internal/domain/dto"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDeletePatientUsecaseInterface is a mock of DeletePatientUsecaseInterface interface.
type MockDeletePatientUsecaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDeletePatientUsecaseInterfaceMockRecorder
	isgomock struct{}
}

// MockDeletePatientUsecaseInterfaceMockRecorder is the mock recorder for MockDeletePatientUsecaseInterface.
type MockDeletePatientUsecaseInterfaceMockRecorder struct {
	mock *MockDeletePatientUsecaseInterface
}

// NewMockDeletePatientUsecaseInterface creates a new mock instance.
func NewMockDeletePatientUsecaseInterface(ctrl *gomock.Controller) *MockDeletePatientUsecaseInterface {
	mock := &MockDeletePatientUsecaseInterface{ctrl: ctrl}
	mock.recorder = &MockDeletePatientUsecaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeletePatientUsecaseInterface) EXPECT() *MockDeletePatientUsecaseInterfaceMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockDeletePatientUsecaseInterface) Execute(ctx context.Context, input dto.DeletePatientInputDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockDeletePatientUsecaseInterfaceMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockDeletePatientUsecaseInterface)(nil).Execute), ctx, input)
}
