// Code generated by MockGen. DO NOT EDIT.
// Source: validate_reset_password_code.usecase.go
//
// Generated by this command:
//
//	mockgen -source validate_reset_password_code.usecase.go -package domain_auth_usecase -destination /home/fernandoviana/Documentos/Appointment-Platform/backend/test/mocks/domain_auth_usecase/mock_validate_reset_password_code.usecase.go
//

// Package domain_auth_usecase is a generated GoMock package.
package domain_auth_usecase

import (
	dto "appointment-platform-backend-backend/internal/domain/dto"
	domain_response "appointment-platform-backend-backend/internal/domain/response"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockValidateResetPasswordCodeUsecaseInterface is a mock of ValidateResetPasswordCodeUsecaseInterface interface.
type MockValidateResetPasswordCodeUsecaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockValidateResetPasswordCodeUsecaseInterfaceMockRecorder
	isgomock struct{}
}

// MockValidateResetPasswordCodeUsecaseInterfaceMockRecorder is the mock recorder for MockValidateResetPasswordCodeUsecaseInterface.
type MockValidateResetPasswordCodeUsecaseInterfaceMockRecorder struct {
	mock *MockValidateResetPasswordCodeUsecaseInterface
}

// NewMockValidateResetPasswordCodeUsecaseInterface creates a new mock instance.
func NewMockValidateResetPasswordCodeUsecaseInterface(ctrl *gomock.Controller) *MockValidateResetPasswordCodeUsecaseInterface {
	mock := &MockValidateResetPasswordCodeUsecaseInterface{ctrl: ctrl}
	mock.recorder = &MockValidateResetPasswordCodeUsecaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidateResetPasswordCodeUsecaseInterface) EXPECT() *MockValidateResetPasswordCodeUsecaseInterfaceMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockValidateResetPasswordCodeUsecaseInterface) Execute(ctx context.Context, input dto.ValidateResetPasswordCodeInputDto) (domain_response.ValidateResetPasswordCodeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(domain_response.ValidateResetPasswordCodeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockValidateResetPasswordCodeUsecaseInterfaceMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockValidateResetPasswordCodeUsecaseInterface)(nil).Execute), ctx, input)
}
