// Code generated by MockGen. DO NOT EDIT.
// Source: auth.usecase.go
//
// Generated by this command:
//
//	mockgen -source auth.usecase.go -package domain_auth_usecase -destination /home/fernandoviana/Documentos/Appointment-Platform/backend/test/mocks/domain_auth_usecase/mock_auth.usecase.go
//

// Package domain_auth_usecase is a generated GoMock package.
package domain_auth_usecase

import (
	dto "appointment-platform-backend-backend/internal/domain/dto"
	domain_response "appointment-platform-backend-backend/internal/domain/response"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAuthUsecaseInterface is a mock of AuthUsecaseInterface interface.
type MockAuthUsecaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAuthUsecaseInterfaceMockRecorder
	isgomock struct{}
}

// MockAuthUsecaseInterfaceMockRecorder is the mock recorder for MockAuthUsecaseInterface.
type MockAuthUsecaseInterfaceMockRecorder struct {
	mock *MockAuthUsecaseInterface
}

// NewMockAuthUsecaseInterface creates a new mock instance.
func NewMockAuthUsecaseInterface(ctrl *gomock.Controller) *MockAuthUsecaseInterface {
	mock := &MockAuthUsecaseInterface{ctrl: ctrl}
	mock.recorder = &MockAuthUsecaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthUsecaseInterface) EXPECT() *MockAuthUsecaseInterfaceMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockAuthUsecaseInterface) Execute(ctx context.Context, input dto.AuthInputDto) (domain_response.AuthResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(domain_response.AuthResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockAuthUsecaseInterfaceMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockAuthUsecaseInterface)(nil).Execute), ctx, input)
}
