// Code generated by MockGen. DO NOT EDIT.
// Source: reset_password.usecase.go
//
// Generated by this command:
//
//	mockgen -source reset_password.usecase.go -package domain_auth_usecase -destination /home/fernandoviana/Documentos/Appointment-Platform/backend/test/mocks/domain_auth_usecase/mock_reset_password.usecase.go
//

// Package domain_auth_usecase is a generated GoMock package.
package domain_auth_usecase

import (
	dto "appointment-platform-backend-backend/internal/domain/dto"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockResetPasswordUsecaseInterface is a mock of ResetPasswordUsecaseInterface interface.
type MockResetPasswordUsecaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockResetPasswordUsecaseInterfaceMockRecorder
	isgomock struct{}
}

// MockResetPasswordUsecaseInterfaceMockRecorder is the mock recorder for MockResetPasswordUsecaseInterface.
type MockResetPasswordUsecaseInterfaceMockRecorder struct {
	mock *MockResetPasswordUsecaseInterface
}

// NewMockResetPasswordUsecaseInterface creates a new mock instance.
func NewMockResetPasswordUsecaseInterface(ctrl *gomock.Controller) *MockResetPasswordUsecaseInterface {
	mock := &MockResetPasswordUsecaseInterface{ctrl: ctrl}
	mock.recorder = &MockResetPasswordUsecaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResetPasswordUsecaseInterface) EXPECT() *MockResetPasswordUsecaseInterfaceMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockResetPasswordUsecaseInterface) Execute(ctx context.Context, input dto.ResetPasswordInputDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockResetPasswordUsecaseInterfaceMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockResetPasswordUsecaseInterface)(nil).Execute), ctx, input)
}
