// Code generated by MockGen. DO NOT EDIT.
// Source: generate_reset_password_code.usecase.go
//
// Generated by this command:
//
//	mockgen -source generate_reset_password_code.usecase.go -package domain_auth_usecase -destination /home/fernandoviana/Documentos/Appointment-Platform/backend/test/mocks/domain_auth_usecase/mock_generate_reset_password_code.usecase.go
//

// Package domain_auth_usecase is a generated GoMock package.
package domain_auth_usecase

import (
	dto "appointment-platform-backend-backend/internal/domain/dto"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGenerateResetPasswordCodeUsecaseInterface is a mock of GenerateResetPasswordCodeUsecaseInterface interface.
type MockGenerateResetPasswordCodeUsecaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockGenerateResetPasswordCodeUsecaseInterfaceMockRecorder
	isgomock struct{}
}

// MockGenerateResetPasswordCodeUsecaseInterfaceMockRecorder is the mock recorder for MockGenerateResetPasswordCodeUsecaseInterface.
type MockGenerateResetPasswordCodeUsecaseInterfaceMockRecorder struct {
	mock *MockGenerateResetPasswordCodeUsecaseInterface
}

// NewMockGenerateResetPasswordCodeUsecaseInterface creates a new mock instance.
func NewMockGenerateResetPasswordCodeUsecaseInterface(ctrl *gomock.Controller) *MockGenerateResetPasswordCodeUsecaseInterface {
	mock := &MockGenerateResetPasswordCodeUsecaseInterface{ctrl: ctrl}
	mock.recorder = &MockGenerateResetPasswordCodeUsecaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGenerateResetPasswordCodeUsecaseInterface) EXPECT() *MockGenerateResetPasswordCodeUsecaseInterfaceMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGenerateResetPasswordCodeUsecaseInterface) Execute(ctx context.Context, input dto.GenerateResetPasswordCodeInputDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockGenerateResetPasswordCodeUsecaseInterfaceMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGenerateResetPasswordCodeUsecaseInterface)(nil).Execute), ctx, input)
}
